import { Listing } from "@/types";

export const mockListings: Listing[] = [
  {
    id: 1,
    title: "Fitness TikTok with 300k Followers",
    platform: "TikTok",
    username: "@fitwithdavid",
    followers: "300,000",
    followersCount: 300000,
    engagement: "5",
    category: "Fitness",
    country: "UK",
    description:
      "Viral fitness content and consistent posting schedule. Brand deals available and audience in the US & UK.",
    price: 12000,
    verified: true,
    featured: true,
    monetized: true,
  },
  {
    id: 2,
    title: "Tech YouTube Channel with 120k Subscribers",
    platform: "YouTube",
    username: "@TechSavvyAlex",
    followers: "120,000",
    followersCount: 120000,
    engagement: "4",
    category: "Tech",
    country: "USA",
    description:
      "Established tech channel with high engagement and steady ad revenue. Includes full transfer and assets.",
    price: 7500,
    verified: true,
    featured: true,
    monetized: true,
  },
  {
    id: 3,
    title: "Travel Instagram Page with 50k Followers",
    platform: "Instagram",
    username: "@wanderlust.sophia",
    followers: "50,000",
    followersCount: 50000,
    engagement: "3",
    category: "Travel",
    country: "Canada",
    description:
      "Beautifully curated travel page with loyal audience and collaboration history with travel brands.",
    price: 2800,
    verified: false,
    featured: false,
    monetized: false,
  },
  {
    id: 4,
    title: "Fashion Pinterest Board with 90k Monthly Views",
    platform: "Pinterest",
    username: "@stylebyalex",
    followers: "15,000",
    followersCount: 15000,
    engagement: "4",
    category: "Fashion",
    country: "USA",
    description:
      "Highly active fashion and design inspiration board with organic traffic and steady audience growth.",
    price: 950,
    verified: false,
    featured: false,
    monetized: false,
  },
  {
    id: 5,
    title: "Music Twitch Channel with 20k Followers",
    platform: "Twitch",
    username: "@SophiaBeats",
    followers: "20,000",
    followersCount: 20000,
    engagement: "6",
    category: "Music",
    country: "Australia",
    description:
      "Active music streaming channel with loyal audience and consistent income from subscribers and donations.",
    price: 3800,
    verified: true,
    featured: false,
    monetized: true,
  },
  {
    id: 6,
    title: "Business LinkedIn Profile with 45k Connections",
    platform: "LinkedIn",
    username: "@markbizpro",
    followers: "45,000",
    followersCount: 45000,
    engagement: "2",
    category: "Business",
    country: "USA",
    description:
      "High-authority LinkedIn profile in B2B marketing space. Excellent engagement from decision-makers.",
    price: 5500,
    verified: true,
    featured: false,
    monetized: false,
  },
  {
    id: 7,
    title: "Gaming Discord Server with 80k Members",
    platform: "Discord",
    username: "@GamingHub",
    followers: "80,000",
    followersCount: 80000,
    engagement: "8",
    category: "Gaming",
    country: "Germany",
    description:
      "Thriving gaming community with active daily members. Multiple monetized channels and premium membership tiers.",
    price: 4200,
    verified: false,
    featured: false,
    monetized: true,
  },
  {
    id: 8,
    title: "Lifestyle Twitter/X Account with 65k Followers",
    platform: "Twitter",
    username: "@lifewithjenna",
    followers: "65,000",
    followersCount: 65000,
    engagement: "3",
    category: "Lifestyle",
    country: "UK",
    description:
      "Engaged lifestyle audience with strong viral tweet history. Monetized via Twitter Blue and brand deals.",
    price: 3100,
    verified: true,
    featured: false,
    monetized: true,
  },
  {
    id: 9,
    title: "Food Facebook Page with 200k Likes",
    platform: "Facebook",
    username: "@tastywithchris",
    followers: "200,000",
    followersCount: 200000,
    engagement: "4",
    category: "Food",
    country: "India",
    description:
      "Massive food page with loyal fanbase across South Asia. Consistent ad revenue and sponsored content history.",
    price: 6800,
    verified: true,
    featured: false,
    monetized: true,
  },
  {
    id: 10,
    title: "Beauty YouTube Channel with 85k Subscribers",
    platform: "YouTube",
    username: "@glowwithsarah",
    followers: "85,000",
    followersCount: 85000,
    engagement: "5",
    category: "Beauty",
    country: "USA",
    description:
      "Beauty and skincare channel with monetized ad revenue. Brand deal ready audience in the 18–34 female demographic.",
    price: 5900,
    verified: true,
    featured: false,
    monetized: true,
  },
];

export const niches = [
  "All niches",
  "Fitness",
  "Tech",
  "Travel",
  "Fashion",
  "Music",
  "Business",
  "Gaming",
  "Lifestyle",
  "Food",
  "Beauty",
  "Education",
  "Sports",
  "Entertainment",
];
